DROP TABLE IF EXISTS dbo.foo;
GO

CREATE TABLE dbo.foo (Id INT PRIMARY KEY);
GO

SET XACT_ABORT ON;
GO

BEGIN TRANSACTION
	INSERT INTO dbo.foo VALUES (1);
	INSERT INTO dbo.foo VALUES (2);
	INSERT INTO dbo.foo VALUES (1);
COMMIT TRANSACTION;
GO

SELECT * FROM dbo.foo;
GO
